# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: networkd
  ethernets:
    enp5s0:
     dhcp4: no
  bridges:
    br0:
      interfaces:
        - enp5s0
      addresses:
        - 192.168.4.82/24
      routes:
        - to: default
          via: 192.168.4.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]


